language: bash

matrix:
  include:
    - os: linux
      dist: bionic

addons:
  apt:
    packages:
    - shellcheck

cache:
  directories:
    - cache

install:
  - curl -sL -o hadolint "https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-$(uname -s)-$(uname -m)"
    && chmod 700 ./hadolint

script:
  - PATH=$PATH:$(pwd) ./test.sh

